[theme]
base = "light"
primaryColor = "#0f766e"
backgroundColor = "#fbfcfe"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#172033"
font = "sans serif"

[server]
maxUploadSize = 20

[browser]
gatherUsageStats = false
