[theme]
base = "light"
primaryColor = "#65a30d"
backgroundColor = "#fbfcfe"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#111827"
font = "sans serif"

[server]
maxUploadSize = 20

[browser]
gatherUsageStats = false
